# Generated by Django 4.2.6 on 2023-10-05 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('sales_network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название сети продаж')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contacts', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_network_contacts', to='sales_network.contacts', verbose_name='Контактная информация')),
                ('supplied_products', models.ManyToManyField(related_name='sales_network_products', to='products.products', verbose_name='Продукция торговой сети')),
            ],
            options={
                'verbose_name': 'Сеть продаж',
                'verbose_name_plural': 'Сети продаж',
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название фабрики')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contacts', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factory_contacts', to='sales_network.contacts', verbose_name='Контактная информация')),
                ('sales_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_network.salesnetwork', verbose_name='Название сети продаж')),
                ('supplied_products', models.ManyToManyField(related_name='factory_products', to='products.products', verbose_name='Фабричная продукция')),
            ],
            options={
                'verbose_name': 'Фабрика',
                'verbose_name_plural': 'Фабрики',
            },
        ),
    ]
