# Generated by Django 4.2.6 on 2023-10-08 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_network', '0005_individualentrepreneur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualentrepreneur',
            name='factory_supplied',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factory_supplier', to='sales_network.factory', verbose_name='Поставщик оборудования(завод)'),
        ),
        migrations.AlterField(
            model_name='individualentrepreneur',
            name='retail_network_supplied',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_entrepreneur_supplier', to='sales_network.retailnetwork', verbose_name='Поставщик оборудования(розница)'),
        ),
    ]
